---
# We want to use both instances for all upstream jobs including the `propose-downstream` one.
# For downstream, we need to pick just one instance (`stg` in our case)
# and redefine it for the `koji_build` and `bodhi_update` jobs.
packit_instances: ["prod", "stg"]
specfile_path: fedora/python-ogr.spec
# https://packit.dev/docs/configuration/#top-level-keys
downstream_package_name: python-ogr
upstream_project_url: https://github.com/packit/ogr
issue_repository: https://github.com/packit/ogr

# we are setting this so we can use packit from ogr's dist-git
# packit can't know what's the upstream name when running from distgit
upstream_package_name: ogr
copy_upstream_release_description: true
actions:
  # we need this b/c `git archive` doesn't put all the metadata in the tarball:
  #   LookupError: setuptools-scm was unable to detect version for '/builddir/build/BUILD/ogr-0.11.1'.
  #   Make sure you're either building from a fully intact git repository or PyPI tarballs.
  create-archive:
    - python3 setup.py sdist --dist-dir .
    - bash -c "ls -1t ./*.tar.gz | head -n 1"
  get-current-version: python3 setup.py --version

srpm_build_deps:
  - python3-pip # "python3 setup.py --version" needs it
  - python3-setuptools_scm

jobs:
  - job: sync_from_downstream
    trigger: commit

  - job: propose_downstream
    trigger: release
    dist_git_branches:
      - fedora-all
      - epel-8

  - job: copr_build
    trigger: pull_request
    targets:
      - fedora-all
      - epel-8
  - job: tests
    trigger: pull_request
    targets:
      - fedora-all
      - epel-8

  - job: production_build
    trigger: pull_request
    scratch: True
    targets:
      - fedora-development

  - job: copr_build
    trigger: commit
    branch: main
    targets:
      - fedora-all
      - epel-8
    project: packit-dev
    list_on_homepage: True
    preserve_project: True

  - job: copr_build
    trigger: commit
    branch: stable
    targets:
      - fedora-stable
      - epel-8
    project: packit-stable
    list_on_homepage: True
    preserve_project: True

  - job: copr_build
    trigger: release
    targets:
      - fedora-all
      - epel-8
    project: packit-releases
    list_on_homepage: True
    preserve_project: True

  # downstream automation:
  - job: koji_build
    trigger: commit
    packit_instances: ["stg"]
    allowed_pr_authors: ["packit-stg", "packit"]
    dist_git_branches:
      - fedora-all
      - epel-8
  - job: bodhi_update
    trigger: commit
    packit_instances: ["stg"]
    dist_git_branches:
      - fedora-latest # branched version, rawhide updates are created automatically
      - fedora-stable
      - epel-8
