# Ogr (test) dependencies.
# To run tests locally via 'make check-in-container'.

FROM quay.io/packit/base:fedora

COPY files/tasks/*.yaml /files/tasks/
COPY files/*.yaml /files/

RUN ansible-playbook -v -c local -i localhost, /files/local-tests-requirements.yaml

WORKDIR /src
