---
- name: Install latest twine for sake of check command
  ansible.builtin.pip:
    name:
      - twine # we need newest twine, b/c of the check command
      - readme_renderer[md]
    state: latest
  become: true
