---
- name: stat {{ project_dir }}
  ansible.builtin.stat:
    path: "{{ project_dir }}"
  tags:
    - no-cache
  register: src_path
- name: Assert project_dir is present
  ansible.builtin.assert:
    that:
      - src_path.stat.isdir
