---
- name: Install dependencies for packit tests
  hosts: all
  vars:
    project_dir: /src
    with_testing: false
  tasks:
    - ansible.builtin.include_tasks: test-tasks/project-dir.yaml
    - ansible.builtin.include_tasks: test-tasks/ogr-deps.yaml
    - ansible.builtin.include_tasks: test-tasks/install-requre.yaml
    - ansible.builtin.include_tasks: test-tasks/git-apis-deps.yaml
    - ansible.builtin.include_tasks: test-tasks/src-path.yaml
    - ansible.builtin.include_tasks: test-tasks/install-ogr.yaml
