---
- name: Install dependencies for PIP ogr
  hosts: all
  tasks:
    - include_tasks: tasks/generic-dnf-requirements.yaml
    - include_tasks: tasks/python-compile-deps.yaml
    - name: Install deps from PyPI
      pip:
        name: "{{ item }}"
      with_items:
        - PyGithub
        - python-gitlab
        - GitPython
        - PyYAML
        - cryptography
        - Deprecated
      become: true
