---
- name: Check if we are not breaking packit
  hosts: all
  tasks:
    - set_fact:
        reverse_dir: "{{ ansible_user_dir }}/{{ zuul.projects['github.com/packit/packit'].src_dir }}"
    - include_tasks: tasks/project-dir.yaml
    - include_tasks: tasks/generic-dnf-requirements.yaml
    - include_tasks: tasks/rpm-test-deps.yaml
    - include_tasks: tasks/packit-requirements.yaml
    - include_tasks: tasks/install-ogr.yaml
    - include_tasks: tasks/packit-tests.yaml
