---
- name: Install RPM dependencies for packit.
  hosts: all
  tasks:
    - include_tasks: tasks/zuul-project-setup.yaml
    - include_tasks: tasks/generic-dnf-requirements.yaml
    - include_tasks: tasks/build-rpm-deps.yaml
    - name: Install deps as RPMs
      dnf:
        name:
          - python3-pygithub
          - python3-gitlab
        state: present
      become: true
