---
- name: This is a recipe for how to run ogr tests
  hosts: all
  tasks:
    - ansible.builtin.include_tasks: tasks/project-dir.yaml
    - ansible.builtin.include_tasks: tasks/rpm-test-deps.yaml
    - ansible.builtin.include_tasks: tasks/install-ogr.yaml
    - ansible.builtin.include_tasks: tasks/configure-git.yaml
    - name: Run tests
      ansible.builtin.command: make check
      args:
        chdir: "{{ project_dir }}"
