---
- name: Install RPM dependencies for ogr
  hosts: all
  tasks:
    - ansible.builtin.include_tasks: tasks/project-dir.yaml
    - ansible.builtin.include_tasks: tasks/generic-dnf-requirements.yaml
    - ansible.builtin.include_tasks: tasks/build-rpm-deps.yaml
    - name: Install deps as RPMs
      ansible.builtin.dnf:
        name:
          - python3-pygithub
          - python3-gitlab
        state: latest
      become: true
